#!/usr/bin/env bash
# shellcheck shell=bash

# Define a logging function to prefix output to the docker logs.
output_to_log() {
    sed  's/^/[s6-init-getlatest-dcs-installer-oneshot] /'
}

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)" | output_to_log
    exit "$exit_code"
}
trap handle_error ERR

download_dcs_server() {
    local MAX_RETRIES=3
    local RETRY_COUNT=0
    while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
        echo -e "New DCS Server download required. Downloading..." | output_to_log
        wget --progress=bar:force -O "$DOWNLOAD_PATH" "$URL" || true
        lsiown abc:users $DOWNLOAD_PATH | output_to_log
        DOWNLOADED_MD5SUM=$(md5sum "$DOWNLOAD_PATH" | awk '{print $1}')
        # Check if the MD5 checksum matches
        if [ "$DOWNLOADED_MD5SUM" == "$MD5SUM" ]; then
            echo -e "Download successful. MD5 checksum matches." | output_to_log
            break
        else
            echo -e "Download failed. MD5 checksum does not match. Retrying in 5 seconds..." | output_to_log
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
        fi
    done
    if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
        echo -e "Download retry count exceeded. Downloading failed." | output_to_log
    fi
}

# Enable immediate exit on error
set -e

URL="https://www.digitalcombatsimulator.com/upload/iblock/ebb/2krwumwaj6vakg2gny13g1t56jral5nq/DCS_World_OpenBeta_Server_modular.exe"
DOWNLOAD_PATH="/config/DCS_World_OpenBeta_Server_modular.exe"

# Note that this method of grabbing the MD5 checksum is fairly brittle!
MD5SUM=$(curl -s "https://www.digitalcombatsimulator.com/en/downloads/world/server_beta/" | grep -o 'MD5:</b> [a-f0-9]\+' | awk '{print $2}')
DOWNLOADED_MD5SUM=$(md5sum "$DOWNLOAD_PATH" | awk '{print $1}')

echo -e "Downloading DCS Server install executable if required: " | output_to_log
# Check if the file exists and is older than 1 day then download.
if [ "$DOWNLOADED_MD5SUM" == "$MD5SUM" ]; then
    echo -e "Already downloaded file matches the correct checksum. Download not needed. " | output_to_log
    echo "Exiting" | output_to_log
    exit 0
else
    download_dcs_server
    echo "Exiting" | output_to_log
    exit 0
fi

# You should never get here.
echo "Exiting" | output_to_log
exit 0