#!/usr/bin/env bash
# shellcheck shell=bash

# Source the log helper after setting the prefix
log_prefix="s6-init-desktop-setup"
source /app/dcs_server/logger_function

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)" 
    exit "$exit_code"
}
trap handle_error ERR

# Function to copy files if hashes differ
copy_if_hash_differs() {
    local source_path="$1"
    local destination_path="$2"

    # Calculate MD5 hash of the source file
    source_hash=$(md5sum "$source_path" | awk '{print $1}')

    # Calculate MD5 hash of the destination file (if it exists)
    if [ -f "$destination_path" ]; then
        destination_hash=$(md5sum "$destination_path" | awk '{print $1}')
    else
        destination_hash=""
    fi

    # Compare hashes
    if [ "$source_hash" = "$destination_hash" ]; then
        echo "Not updating $destination_path as file already matches." 
    else
        # Copy the file
        cp "$source_path" "$destination_path"
        echo "Updating $destination_path as file does not match source file from the Docker image." 
        lsiown -R abc:users $destination_path 
    fi
}

# Wait for volumes to be fully mounted.
sleep 5

# Ensure that the wine prefix is owned by the user from the container.
lsiown -R abc:users /config/Desktop 

# copy_if_hash_differs SRC DEST
copy_if_hash_differs "/app/dcs_server/desktop-setup/Run_DCS_Install.desktop" "/config/Desktop/Run_DCS_Install.desktop"

echo "Exiting" 
exit 0