#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Source the log helper after setting the prefix
log_prefix="s6-init-dcssb-auto-start-longrun"
source /app/dcs_server/logger_function

handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"
    exit "$exit_code"
}
trap handle_error ERR

# Get / set env vars and timeout value for server check interval.
DCSSBAUTOSTART="${DCSSBAUTOSTART:-0}"
TIMEOUT="${TIMEOUT:-30}"

# Check if DCSSBAUTOINSTALL environment variable is set to 1
if [ "${DCSSBAUTOSTART}" != "1" ]; then
    echo "DCSSBAUTOSTART is not set to 1. Exiting."
    sleep ${TIMEOUT}
    exit 0
fi

# Define the path to the DCSSB virtual environment
VENV_PATH="/config/.wine/drive_c/users/abc/.dcssb"

# Check if the directory exists to indicate if the manual first install has happened
if [ ! -d "$VENV_PATH" ]; then
    echo "DCSSBAUTOSTART set to auto start but no Python virtual environment appears to exist."
    echo "Please ensure you have manually installed DCSServerBot prior to auto starting."
    sleep ${TIMEOUT}
    exit 1
fi

# What lies below is cursed.
# First update pip
sudo -E -u abc bash <<EOF
wine cmd.exe /c "%USERPROFILE%\.dcssb\Scripts\python.exe -m pip install --upgrade pip"
EOF

# Now update the venv packages as the DCSSB update.py won't do so due to logic that won't trigger
sudo -E -u abc bash <<EOF
wine cmd.exe /c "%USERPROFILE%\.dcssb\Scripts\python.exe -m pip install -r %USERPROFILE%\DCSServerBot\requirements.txt"
EOF

# Now start up the bot
sudo -E -u abc bash <<'EOF'
export DISPLAY=:1.0  # Set the display to the main X server display
xfce4-terminal --title=DCSServerbot --default-working-directory=/config/.wine/drive_c/users/abc/DCSServerBot  -e 'wine /config/.wine/drive_c/users/abc/DCSServerBot/run.cmd'
EOF
