#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Source the log helper after setting the prefix
log_prefix="s6-init-dcs-retribution-remote-auto-installer-updater-oneshot"
source /app/dcs_server/logger_function

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"  
    exit "$exit_code"
}
trap handle_error ERR

# Get/set default value for ENABLE_DCS_RETRIBUTION_REMOTE if not already set
ENABLE_DCS_RETRIBUTION_REMOTE="${ENABLE_DCS_RETRIBUTION_REMOTE:-0}"
echo -e "ENABLE_DCS_RETRIBUTION_REMOTE=$ENABLE_DCS_RETRIBUTION_REMOTE" 

if [ "${ENABLE_DCS_RETRIBUTION_REMOTE}"  -ne 1 ]; then
    echo "No ENABLE_DCS_RETRIBUTION_REMOTE variable set, skipping DCS Retribution installation or update."
    exit 0
fi

# Source DCS Dirs finder helper
# This sets the following variables:
# WINE_user_saved_game_dir="/config/.wine/drive_c/users/abc/Saved Games"
# WINE_program_files_dir="/config/.wine/drive_c/Program Files"
# DCS_saved_games_dir_open_beta
# DCS_saved_games_dir_release
# DCS_saved_games_dir_current
# DCS_install_dir_openbeta
# DCS_install_dir_release
# DCS_bin_dir_openbeta
# DCS_bin_dir_release
source /app/dcs_server/find_dcs_dirs_function

[ -d "${DCS_saved_games_dir_current}/Missions" ] || sudo -E -u abc mkdir -p "${DCS_saved_games_dir_current}/Missions"
[ -d "${DCS_saved_games_dir_current}/MissionEditor/UnitPayloads" ] || sudo -E -u abc mkdir -p "${DCS_saved_games_dir_current}/MissionEditor/UnitPayloads"

echo "Installing DCS Retribution"

RETRIBUTION_REMOTE_REPO="${RETRIBUTION_REMOTE_REPO:-omltcat/dcs-retribution-remote}"
echo -e "RETRIBUTION_REMOTE_REPO=$RETRIBUTION_REMOTE_REPO"
Retribution_remote_latest_release_manifest=$(curl -s "https://api.github.com/repos/${RETRIBUTION_REMOTE_REPO}/releases/latest")
Retribution_remote_download_url=$(echo $Retribution_remote_latest_release_manifest | jq -r .assets[0].browser_download_url)
Retribution_remote_tag=$(echo $Retribution_remote_latest_release_manifest | jq -r .name)

Retribution_remote_zip_dl_path="${WINE_user_saved_game_dir}/dcs-retribution-remote-$Retribution_remote_tag.zip"
Retribution_remote_install_dir="${WINE_user_saved_game_dir}/dcs-retribution-remote"
Retribution_remote_cfg_file_path="${Retribution_remote_install_dir}/config.yaml"

Retribution_remote_present_version_file="${WINE_user_saved_game_dir}/dcs-retribution-remote.version.txt"

echo "Checking if DCS Retribution Remote latest ${Retribution_tag} needs to be downloaded..."

# If there's no file or the version is missing, we need to update
if [ ! -f "$Retribution_remote_present_version_file" ] || grep -v "$Retribution_remote_tag" "$Retribution_remote_present_version_file"; then
    echo "Downloading $Retribution_remote_download_url"
    sudo -E -u abc wget "$Retribution_remote_download_url" -O "$Retribution_remote_zip_dl_path" && \
    sudo -E -u abc unzip -qq -o "$Retribution_remote_zip_dl_path" -d "${Retribution_remote_install_dir}" && \
    rm "$Retribution_remote_zip_dl_path" && \
    sudo -E -u abc echo "$Retribution_remote_tag" > "$Retribution_remote_present_version_file"
fi

# Function to convert Linux-like pathing to WINE Windows-like pathing
convert_path() {
local path="$1"
# i.e. Replace '/config/.wine/drive_c' with 'C:/'
echo "${path//\/config\/.wine\/drive_c/C:}"
}
# Generate retribution_preferences.json using heredoc
sudo -E -u abc cat <<EOF > "$Retribution_remote_cfg_file_path"
server:
  dcs_mission_dir: "$(convert_path "$DCS_saved_games_dir_current")/Missions"
  dcs_server_exe: "$(convert_path "$DCS_install_dir_release/bin/DCS_server.exe")"
  max_running_time: 0

users:
- username: abc
  password: "${PASSWORD:-123123123}"

app:
  host: "0.0.0.0"
  port: 9099
  https: true
  debug: false
  allowed_filenames:
  - retribution_nextturn.miz
  - liberation_nextturn.miz
  allowed_max_size: 0
EOF

echo "Generated default retribution remote config: $Retribution_remote_cfg_file_path"


echo "Adding desktop shortcut."
# Run subsequent commands as user 'abc' using sudo
sudo -E -u abc bash <<EOF
# Source the desktop shortcut creation function
# target_executable="$1"
# icon_path="$2"
# name="$3"
# terminalbool="$4"
# workdir="$5"
source /app/dcs_server/create_desktop_shortcut_function

# Create the desktop shortcut
create_desktop_shortcut "bash -c 'SERVER_BIND_ADDRESS=\"0.0.0.0\" wine \"$Retribution_remote_install_dir/retribution_remote.exe\"'" \
                        "$DCS_install_dir_release/FUI/DCS-1.ico" \
                        "DCS Retribution Remote" \
                        "false" \
                        "$Retribution_remote_install_dir"
EOF

echo "DCS Retribution Remote installation complete."
exit 0
