#!/usr/bin/env bash
# shellcheck shell=bash

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"
    exit "$exit_code"
}
trap handle_error ERR

# Define a logging function to prefix output to the docker logs.
output_to_log() {
    sed  's/^/[s6-init-winepreqs-oneshot] /'
}

# Redirect all subsequent output to the logging function
exec 3>&1
exec > >(output_to_log)

# Enable immediate exit on error
set -e

# Ensure that the wine prefix is owned by the user from the container.
lsiown -R abc:users /config/.wine
lsiown -R abc:users /config/.cache

sudo -u abc winecfg

# Install the wine dependencies.
# Note that this will not reinstall the dependencies if they are already installed.
sudo -u abc /usr/bin/winetricks --unattended d3dcompiler_43
sudo -u abc /usr/bin/winetricks --unattended d3dx11_43
sudo -u abc /usr/bin/winetricks --unattended d3dcompiler_47
sudo -u abc /usr/bin/winetricks --unattended win10
echo "Exiting"
exit 0