#!/usr/bin/env bash
# shellcheck shell=bash

# Source the log helper after setting the prefix
log_prefix="s6-init-winepreqs-oneshot"
source /app/dcs_server/logger_function

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"  
    exit "$exit_code"
}
trap handle_error ERR

# Enable immediate exit on error
set -e

# Wait for volumes to be fully mounted.
sleep 5

# Ensure that the wine prefix is owned by the user from the container.
mkdir -p /config/.wine /config/.cache
lsiown -R abc:users /config/.wine 
lsiown -R abc:users /config/.cache 

sudo -u abc winecfg

# Add required DLL overrides
echo "Installing Wine DLL overrides"
sudo -u abc /usr/bin/wine reg add 'HKCU\Software\Wine\DllOverrides' /v wbemprox /t REG_SZ /d 'native' /f

# Install the wine dependencies.
# Note that this will not reinstall the dependencies if they are already installed.
sudo -u abc /usr/bin/winetricks --unattended d3dcompiler_43 
sudo -u abc /usr/bin/winetricks --unattended d3dx11_43 
sudo -u abc /usr/bin/winetricks --unattended d3dcompiler_47 
sudo -u abc /usr/bin/winetricks --unattended win10 

echo "Wine installations complete, Exiting." 

exit 0