#!/usr/bin/env bash
# shellcheck shell=bash
#
# Note - when Eagle Dynamics update the DCS server from Open Beta to no more Open Beta paths changed
# as follows -
#
# Saved Games dirs
# From: "/config/.wine/drive_c/users/abc/Saved Games/DCS.openbeta_server"
# To: "/config/.wine/drive_c/users/abc/Saved Games/DCS.release_server/"
#
# Installation folder
# From: "/config/.wine/drive_c/Program Files/Eagle Dynamics/DCS World OpenBeta Server"
# To: "/config/.wine/drive_c/Program Files/Eagle Dynamics/DCS World Server"
#
# This script will define some useful variables to store paths then
# parse and check a subset to see if these folders exist and flag as such by settings other variables.

# Path variables
WINE_appdata_local_dir="/config/.wine/drive_c/users/abc/AppData/Local/"
WINE_appdata_roaming_dir="/config/.wine/drive_c/users/abc/AppData/Roaming/"
WINE_user_saved_game_dir="/config/.wine/drive_c/users/abc/Saved Games"
WINE_program_files_dir="/config/.wine/drive_c/Program Files"

# Path variables actually checked
DCS_saved_games_dir_open_beta="${WINE_user_saved_game_dir}/DCS.openbeta_server"
DCS_saved_games_dir_release="${WINE_user_saved_game_dir}/DCS.server"
DCS_install_dir_openbeta="${WINE_program_files_dir}/Eagle Dynamics/DCS World OpenBeta Server"
DCS_install_dir_release="${WINE_program_files_dir}/Eagle Dynamics/DCS World Server"

# Additional helper path variables
DCS_bin_dir_openbeta="${DCS_install_dir_openbeta}/bin"
DCS_bin_dir_release="${DCS_install_dir_release}/bin"

# Check if Saved Games directories exist
if [[ -d "$DCS_saved_games_dir_open_beta" ]]; then
    DCS_saved_games_dir_open_beta_presence_boolean=true
else
    DCS_saved_games_dir_open_beta_presence_boolean=false
fi

if [[ -d "$DCS_saved_games_dir_release" ]]; then
    DCS_saved_games_dir_release_presence_boolean=true
else
    DCS_saved_games_dir_release_presence_boolean=false
fi

# Check if Installation folders exist
if [[ -d "$DCS_install_dir_openbeta" ]]; then
    DCS_install_dir_openbeta_presence_boolean=true
else
    DCS_install_dir_openbeta_presence_boolean=false
fi

if [[ -d "$DCS_install_dir_release" ]]; then
    DCS_install_dir_release_presence_boolean=true
else
    DCS_install_dir_release_presence_boolean=false
fi

# Log the results to stdout
#echo "DCS Server OpenBeta Saved Games directory exists:" $DCS_saved_games_dir_open_beta_presence_boolean
#echo "DCS Server Release Saved Games directory exists:" $DCS_saved_games_dir_release_presence_boolean
#echo "DCS Server OpenBeta Installation folder exists:" $DCS_install_dir_openbeta_presence_boolean
#echo "DCS Server Release Installation folder exists:" $DCS_install_dir_release_presence_boolean
