version: '3.3'
services:
  dcs-world-dedicated-server:
    container_name: dcs-world-dedicated-server
    hostname: dcs-world-dedicated-server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=$VNCPASSWORD
      - DCSAUTOINSTALL=${DCSAUTOINSTALL:-0}
      - DCSMODULES=${DCSMODULES:-}
      - FORCEREINSTALL=${FORCEREINSTALL:-0}
      - AUTOSTART=${AUTOSTART:-0}
      - TIMEOUT=${TIMEOUT:-30}
      - ENABLE_DCS_RETRIBUTION=${ENABLE_DCS_RETRIBUTION:-0}
      # ENABLE_DCS_RETRIBUTION also requires the DOCKER_MODS Environment variable set as below to function
      # DOCKER_MODS=aterfax/dcs-world-dedicated-server-mod-retribution:latest
      - DCSSBAUTOINSTALL=${DCSSBAUTOINSTALL:-0}
      - DCSSBAUTOSTART=${DCSSBAUTOSTART:-0}
      # DCS Server Bot requires you have added DOCKER_MODS=aterfax/dcs-world-dedicated-server-mod-dcsserverbot:latest
    ports:
      # Webtop WebGUI ports    
      - '3000:3000/tcp' # Webtop HTTP port - TCP only.
      - '3001:3001/tcp' # Webtop HTTPs port - TCP only.

      # DCS server Ports      
      - '10308:10308/tcp' # Multiplayer game traffic - TCP.
      - '10308:10308/udp' # Multiplayer game traffic - UDP.      
      #- '10309:10309/tcp' # Multiplayer game VOIP traffic - TCP - Uncomment if in game VOIP is desired.
      #- '10309:10309/udp' # Multiplayer game VOIP traffic - UDP - Uncomment if in game VOIP is desired.      
      #- '8088:8088' # Uncomment to enable remote web control webGUI from the Eagle Dynamics website - TCP only.

      # Tacview ports
      #- '42674:42674/tcp' # Uncomment to enable TacView Real-time Telemetry if in use - TCP only.
      #- '42675:42675/tcp' # Uncomment to enable TacView Remote Control if in use - TCP only.

      # DCS SimpleRadio Standalone (DCS-SRS) ports
      #- '5002:5002/tcp' # Uncomment to enable DCS SimpleRadio Standalone (DCS-SRS) - TCP and UDP.
      #- '5002:5002/udp' # Uncomment to enable DCS SimpleRadio Standalone (DCS-SRS) - TCP and UDP.      
    volumes:
      - '${HOME}/dcs-world-dedicated-server:/config/'
    # Setting seccomp to unconfined with security_opt is necessary if you encounter 'Failed to execute child process "bash": Failed to fdwalk: Operation not permitted' errors.
    # You should not unconfine unless necessary.
    # See also: https://docs.linuxserver.io/images/docker-webtop/#application-setup
    #security_opt:
      #- seccomp=unconfined
    restart: always
    image: aterfax/dcs-world-dedicated-server
