#!/bin/bash
# shellcheck shell=bash

# Source DCS Dirs finder helper
# This sets the following variables:
# DCS_saved_games_dir_open_beta
# DCS_saved_games_dir_release
# DCS_saved_games_dir_current
# DCS_saved_games_dir_previous_1
# DCS_install_dir_openbeta
# DCS_install_dir_release
source /app/dcs_server/find_dcs_dirs_function

create_desktop_shortcut() {
    target_executable="$1"
    icon_path="$2"
    name="$3"
    terminalbool="$4"
    desktop_file="$HOME/Desktop/${name// /_}.desktop"  # Replace spaces with underscores

    # Create the desktop shortcut file
    echo "[Desktop Entry]" > "$desktop_file"
    echo "Version=1.0" >> "$desktop_file"
    echo "Name=$name" >> "$desktop_file"
    echo "Comment=$name" >> "$desktop_file"
    echo "Exec=$target_executable" >> "$desktop_file"
    echo "Icon=$icon_path" >> "$desktop_file"
    echo "Terminal=$terminalbool" >> "$desktop_file"
    echo "Type=Application" >> "$desktop_file"
    echo "Categories=Game;" >> "$desktop_file"

    # Make the desktop shortcut executable
    chmod +x "$desktop_file"
}

# Read the autoinstaller environment variables
DCSAUTOINSTALL="${DCSAUTOINSTALL:-0}"
DCSMODULES="${DCSMODULES:-}"

# Validate DCSAUTOINSTALL as boolean (1 or 0)
if [[ "$DCSAUTOINSTALL" != "0" && "$DCSAUTOINSTALL" != "1" ]]; then
    echo "Invalid value for DCSAUTOINSTALL. Should be 0 or 1."
    exit 1
fi

if [ "$DCSAUTOINSTALL" -eq 1 ]; then
    # Validate DCSMODULES using regex (alphanumeric, underscores, or spaces)
    if ! [[ "$DCSMODULES" =~ ^[A-Za-z0-9_[:space:]-]*$ ]]; then
        echo "Invalid value for DCSMODULES. The list should be supplied as a whitespace separated list of modules as per https://forum.dcs.world/topic/324040-eagle-dynamics-modular-dedicated-server-installer/"
        exit 1
    fi
fi

# Start the installer
cd /config
FILE="DCS_updater_64bit.zip"
URL="https://updates.digitalcombatsimulator.com/files/$FILE"

# Download the file if missing or older than 14 days
if [ ! -f "$FILE" ] || [ $(find "$FILE" -mtime +14) ]; then
    echo "Downloading DCS Updater ZIP..."
    wget -qO "$FILE" "$URL" || { echo "DCS Updater ZIP Download failed!"; exit 1; }
    unzip -tq "$FILE" || { echo "DCS Updater ZIP Validation failed!"; exit 1; }
    unzip -qo "$FILE" && echo "DCS Updater ZIP Extraction complete."
fi

if [ ! -d "$DCS_install_dir_release/bin" ]; then
    mkdir -p "$DCS_install_dir_release/bin"
fi

if [ ! -d "$DCS_install_dir_release/Config" ]; then
    mkdir -p "$DCS_install_dir_release/Config"
fi

if [ ! -d "$DCS_saved_games_dir_current" ]; then
    mkdir -p "$DCS_saved_games_dir_current"
fi

if [ ! -f "$DCS_install_dir_release/Config/lang.txt" ]; then
    echo -n "EN" > "$DCS_install_dir_release/Config/lang.txt"
fi

if [ ! -f "$DCS_install_dir_release/dcs_variant.txt" ]; then
    echo -n "dcs_server.release" > "$DCS_install_dir_release/dcs_variant.txt"
fi

if [ ! -f "$DCS_install_dir_release/autoupdate.cfg" ] ; then
	# set "launch" key to null to prevent updater from starting server
	cat <<-EOF >"$DCS_install_dir_release/autoupdate.cfg"
		{
		 "WARNING": "DO NOT EDIT this file. You may break your install!",
		 "branch": "dcs_server.release",
		 "arch": "x86_64",
		 "lang": "EN",
		 "modules": [
         "WORLD"
		 ],
		 "launch": null
		}
	EOF
fi

# We want to avoid the updater racecondition where it fails to update itself
cp DCS_updater.exe "$DCS_install_dir_release/bin/DCS_updater_initial.exe"
cd "$DCS_install_dir_release/bin"

wine DCS_updater_initial.exe --quiet update &
# Ensure the updater process has finished before cleanup
start_time=$(date +%s)
while pgrep -f DCS_updater_initial.exe >/dev/null; do
    elapsed=$(( $(date +%s) - start_time ))
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Waiting for DCS_updater_initial.exe to finish... Elapsed time: ${elapsed} seconds"
    sleep 10
done
# Rename it again so subsequent logic is not broken
mv DCS_updater_initial.exe DCS_updater.exe

# Remove broken shortcuts.
rm /config/Desktop/Local\ Web\ GUI.desktop
rm /config/Desktop/DCS\ World\ OpenBeta\ Server.desktop

# Create working shortcuts.
create_desktop_shortcut "wine \"${DCS_install_dir_release}/bin/DCS_updater.exe\"" \
                        "${DCS_install_dir_release}/FUI/DCS-1.ico" \
                        "Run DCS Updater" \
                        "false"

create_desktop_shortcut "wine \"${DCS_install_dir_release}/bin/DCS_server.exe\"" \
                        "${DCS_install_dir_release}/FUI/DCS-1.ico" \
                        "Run DCS Server" \
                        "false"

create_desktop_shortcut "xdg-open \"${DCS_install_dir_release}/WebGUI/index.html\""\
                        "${DCS_install_dir_release}/FUI/DCS-1.ico" \
                        "Open DCS Server WebGUI" \
                        "false"

create_desktop_shortcut "/app/dcs_server/wine-dedicated-dcs-automated-installer/dcs-dedicated-server-module-installer.sh"\
                        "${DCS_install_dir_release}/FUI/DCS-1.ico" \
                        "Run DCS Module Installer" \
                        "true"

create_desktop_shortcut "xdg-open \"${DCS_saved_games_dir_current}/\""\
                        "folder" \
                        "DCS Saved Games Dir" \
                        "false"

create_desktop_shortcut "xdg-open \"${DCS_install_dir_release}/\""\
                        "folder" \
                        "DCS Install Dir" \
                        "false"

# Run the module installer

# Validate DCSMODULES using regex (alphanumeric, underscores, or spaces).
# Works for installations or updates.
if [[ "$DCSMODULES" =~ ^[A-Za-z0-9_[:space:]-]*$ ]]; then
    echo "Modules installation starting."
    /app/dcs_server/wine-dedicated-dcs-automated-installer/dcs-dedicated-server-module-installer.sh install "$DCSMODULES"
    echo
    echo "Install complete."
    exit 0
fi

echo "Manual installation, please select modules to install/"
/app/dcs_server/wine-dedicated-dcs-automated-installer/dcs-dedicated-server-module-installer.sh
echo
echo "Install complete."
exit 0
